### ISSUE TITLE
MGLAG Role

### ISSUE THREAD

**Issue by jorgebonilla** [JNPRAutomate/ansible-junos-evpn-vxlan#29]
Damien, 
Do you think we can create an MCLAG Role, in order to automate/templatize an MCLAG+CLOS+VXLAN architecture? Or is that done somewhere else?
Thoughts?

**Comment by dgarros** [comment]
Hi @jorgebonilla,
Thanks for the proposal. 
We don't support MC-LAG and EVPN at the same time but you can use EVPN/ESI to provide multi-homing, it's even better than MC-LAG
The role [overlay-evpnaccess](https://github.com/JNPRAutomate/ansible-junos-evpn-vxlan/tree/master/roles/overlay-evpn-access) let you create a LAG using ESI to have a device connected to multiple TOR.
Please let me know if this is good fit for your need.
Thanks
Damien
